[#25] Jenkins를 이용한 CD 구현
f-lab-edu/ludensdomain pull request #62
Opened 2021-06-24 04:36 UTC by daakludens

배포 자동화를 위한 Jenkinsfile 작성

2021-07-13 02:52 UTC, f-lab-dev approved these changes

2021-07-13 02:53 UTC, f-lab-dev requested changes
아 잘못눌렀습니다~

2021-08-03 15:57 UTC, daakludens commented
IntelliJ에서 커밋 및 푸시 했을 때 Jenkinsfile로 Jenkins를 통해 배포 로그까지 확인했습니다.

2021-08-04 01:35 UTC, f-lab-dev approved these changes

2021-08-04 11:26 UTC, merged